title: "Diaries of a Modern Ninja"
description: "Nima's Diaries"
author:
  name: "Nima"
  twitter: "cSh4rkx"

url: "https://nima.ninja"
baseurl: ""

source: .
destination: ./_site
permalink: /:categories/:year/:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

#google_analytics: [Your Google Analytics tracking ID]

# Custom variables
owner : "Nima"
year : "2023"

twitter:
  username: cSh4rkx
  card: summary_large_image

# Contact
social:
  name: cSh4rk
  email: "nima@nima.ninja"
  email2: "csh4rk0x00@protonmail.com"
  github: "cSh4rk"
  githubname: "Shark"
  twitter: "cSh4rkx"
  twittername: "Shark"
  mastodon: "https://infosec.exchange/@cSh4rk"
  mastodonhandle: "@cSh4rk"
  mastodonname: "Shark"
  linkedin: 
  pgpkey: "CEE9A66A2F5C6187E4242B0425669795B037FEF2.asc"
  hackthebox: "768488"
  discorduser: "csh4rk"
  discordserver: "YReXPS4YaA"
  discordservername: "Legendary NOoBs"
  wickrme: "csh4rk"
  tellonym: "__nima__"
  links:
    - https://twitter.com/cSh4rkx
    - https://github.com/cSh4rk
# End of Contact
