title: "Diaries of a Modern Ninja"
description: "Nima's Diaries"
author:
  name: "Nima"
  twitter: "cSh4rk"

url: "https://nima.ninja"
baseurl: ""

source: .
destination: ./_site
permalink: /:categories/:year/:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-algolia

#google_analytics: [Your Google Analytics tracking ID]

# Custom variables
owner : "Nima"
year : "2022"

twitter:
  username: cSh4rk
  card: summary_large_image

# Contact
social:
  name: cSh4rk
  email: "nima@nima.ninja"
  github: "cSh4rk"
  twitter: "cSh4rk"
  linkedin:
  pgpkey: "CEE9A66A2F5C6187E4242B0425669795B037FEF2.asc"
  hackthebox: "768488"
  discorduser: "nima#6874"
  discordserver: "YReXPS4YaA"
  discordservername: "Legendary NOoBs"
  wickrme: "csh4rk"
  tellonym: "__nima__"
  links:
    - https://twitter.com/cSh4rk
    - https://github.com/cSh4rk
# End of Contact

algolia:
   application_id: P3FVGWTLAB
   index_name: jekyll
   search_only_api_key: caee2236ed28fdff4d0c0f8812d3e7be
