title: Delete the Matrix
tagline: Exploiting, Experimenting, && Exploring
description: "A blog about Exploiting, Experimenting, and Exploring the universe"
author:
  name: "CamoCatX"

url: "https://camocatx@github.io"

github_username:  CamoCatX
strict_front_matter: true
baseurl: ""
image: /favicon.png
source: .
destination: ./_site
permalink: /:categories/:year/:title
paginate: 3
paginate_path: /page/:num/


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  
# Custom variables
owner : "CamoCatX"
year : "2024"

encoding: utf-8
locale: en
verbose: false
quiet: true

# Contact
social:
  name: CamoCatX
  email: "camocatx@proton.me"
  github: "camocatx"
  githubname: "CamoCatX"
  links:
    - https://github.com/CamoCatX

  compress_html:
    clippings: all
    comments: all
    endings: all #[html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
    profile: false
    blanklines: false
    ignore:
      envs: []

exclude:
  - .gitignore
  - README.md
  - LICENSE
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/

sass:
    sass_dir : _sass
    style    : compressed
