title: Delete the Matrix
tagline: Exploiting, Experimenting, && Exploring
description: "A Blog about Exploiting, Experimenting, and Exploring the Universe"
author:
  name: "CamoCatX"
  url: "deletethematrix.com"
  
strict_front_matter: true

baseurl: ""
source: .
destination: ./_site
permalink: /:categories/:year/:title
paginate: 3
paginate_path: /page/:num/

safe: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      sitemap: true

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - webrick
  - jekyll-loading-lazy
  - jekyll-link-attributes
  - jekyll-minifier

encoding: utf-8
locale: en

# Contact
social:
  name: CamoCatX
  email: "camocatx@proton.me"
  github: "camocatx"
  githubname: "CamoCatX"
  links:
    - https://github.com/CamoCatX

  compress_html:
    clippings: all
    comments: all
    endings: false # [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
    blanklines: false
    ignore:
      envs: []

exclude:
  - .gitignore
  - .vscode/
  - README.md
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
  - seo-analyzer.rb
sass:
    style: compressed

jekyll-minifier:
  preserve_php: false                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: true              # Default: false
  compress_css: true                # Default: tue  # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: true # Default: false
  remove_http_protocol: true      # Default: false
  remove_https_protocol: false      # Default: fals
  preserve_line_breaks: false       # Default: 
  simple_boolean_attributes: false