title: Delete the Matrix
description: "Information is Power. Knowledge is Freedom."
author:
  name: "CamoCatX"
  url: "deletethematrix.com"
  
strict_front_matter: true

baseurl: ""
source: .
destination: ./_site
permalink: /:categories/:year/:title
paginate: 3
paginate_path: /page/:num/

safe: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      sitemap: true

future: true
plugins:
  - jekyll-paginate


encoding: utf-8
locale: en

# Contact
social:
  name: CamoCatX
  email: "camocatx@proton.me"
  github: "camocatx"
  githubname: "CamoCatX"
  links:
    - https://github.com/CamoCatX

  compress_html:
    clippings: all
    comments: all
    endings: false # [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
    blanklines: false
    ignore:
      envs: []

exclude:
  - .gitignore
  - .vscode/
  - README.md
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
  - seo-analyzer.rb
sass:
    style: compressed