title: Diaries of a Modern Ninja
description: "Nima's Diaries"
author:
  name: "Nima"
  twitter: cybersh4rk

url: "https://nima.ninja"
baseurl: ""

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

#google_analytics: [Your Google Analytics tracking ID]

# Custom variables
owner : "Nima"
year : "2021"

twitter:
  username: cybersh4rk
  card: summary_large_image
  
# Social Media
social:
  name: cSh4rk
  github: "csh4rk"
  twitter: "cybersh4rk"
  linkedin: ""
  links:
    - https://twitter.com/cybersh4rk
    - https://github.com/csh4rk
